// tslint:disable:max-line-length
import { Checklist } from '../checklist.interface';

const data: Checklist = {
    id: 'sl-alliance',
    items: [
        { key: 'leveling', name: 'Leveling', type: 'header', level: 0 },

        { key: 'leveling-bastion', name: 'Bastion', type: 'header', level: 1 },
        { key: 'leveling-bastion-mainquests', name: 'The Path to Ascension', type: 'achievement', id: 14281 },
        { key: 'leveling-bastion-sidequests', name: 'Sojourner of Bastion', type: 'achievement', id: 14801 },
        { key: 'leveling-bastion-dungeon', name: 'Necrotic Wake', type: 'quest', id: 60057 },

        { key: 'leveling-maldraxxus', name: 'Maldraxxus', type: 'header', level: 1 },
        { key: 'leveling-maldraxxus-mainquests', name: 'Blade of the Primus', type: 'achievement', id: 14206 },
        { key: 'leveling-maldraxxus-sidequests', name: 'Sojourner of Maldraxxus', type: 'achievement', id: 14799 },
        { key: 'leveling-maldraxxus-dungeon', name: 'Plaguefall', type: 'quest', id: 59520 },

        { key: 'leveling-ardenweald', name: 'Ardenweald', type: 'header', level: 1 },
        { key: 'leveling-ardenweald-mainquests', name: 'Awaken, Ardenweald', type: 'achievement', id: 14164 },
        { key: 'leveling-ardenweald-sidequests', name: 'Sojourner of Ardenweald', type: 'achievement', id: 14800 },
        { key: 'leveling-ardenweald-dungeon', name: 'Tirna Scithe', type: 'quest', id: 62371 },

        { key: 'leveling-revendreth', name: 'Revendreth', type: 'header', level: 1 },
        { key: 'leveling-revendreth-mainquests', name: 'The Master of Revendreth', type: 'achievement', id: 13878 },
        { key: 'leveling-revendreth-sidequests', name: 'Sojourner of Revendreth', type: 'achievement', id: 14798 },
        { key: 'leveling-revendreth-dungeon', name: 'Halls of Atonement', type: 'quest', id: 58092 },

        { key: 'leveling-general', name: 'General', type: 'header', level: 1 },
        { key: 'leveling-general-50', name: 'Level 50', type: 'level', max: 50 },
        { key: 'leveling-general-60', name: 'Level 60', type: 'level', max: 60 },

        { key: 'leveling-gear', name: 'Gear', type: 'header', level: 1 },
        { key: 'leveling-gear-158', name: 'Item Level 158 / Superior', type: 'avg-item-level', max: 158 },

        { key: 'campaign', name: 'Covenant Campaign', type: 'header', level: 0 },
        { key: 'campaign-choosingyourpurpose', name: 'Choosing Your Purpose', type: 'achievement', id: 14627 },
        { key: 'campaign-renown10', name: 'Renown 10', type: 'renown', threshold: 10 },
        { key: 'campaign-renown20', name: 'Renown 20', type: 'renown', threshold: 20 },
        { key: 'campaign-renown30', name: 'Renown 30', type: 'renown', threshold: 30 },
        { key: 'campaign-renown40', name: 'Renown 40', type: 'renown', threshold: 40 },
        { key: 'campaign-torghast', name: 'The Captive King', type: 'quest', id: 61730 },
        { key: 'campaign-finished-kyrian', name: 'Covenant Campaign', covenant: 'Kyrian', type: 'quest', id: 62557 },
        { key: 'campaign-finished-necrolords', name: 'Covenant Campaign', covenant: 'Necrolord', type: 'quest', id: 62406 },
        { key: 'campaign-finished-nightfae', name: 'Covenant Campaign', covenant: 'Night Fae', type: 'quest', id: 60108 },
        { key: 'campaign-finished-venthyr', name: 'Covenant Campaign', covenant: 'Venthyr', type: 'quest', id: 58407 },

        { key: 'chainsofdomination', name: 'Chains of Domination', type: 'header', level: 0 },
        { key: 'chainsofdomination-renown-50', name: 'Renown 50', type: 'renown', threshold: 50 },
        { key: 'chainsofdomination-renown-60', name: 'Renown 60', type: 'renown', threshold: 60 },
        { key: 'chainsofdomination-renown-70', name: 'Renown 70', type: 'renown', threshold: 70 },
        { key: 'chainsofdomination-renown-80', name: 'Renown 80', type: 'renown', threshold: 80 },
        { key: 'chainsofdomination-story', name: 'Chains of Domination', type: 'achievement', id: 14961 },
        { key: 'chainsofdomination-boxofmanythings', name: 'Box of Many Things', type: 'quest', id: 64216 },
        { key: 'chainsofdomination-tazavesh-intro', name: 'The Veiled Market', type: 'quest', id: 63985 },
        { key: 'chainsofdomination-establishing-the-archive', name: 'Establishing the Archive', type: 'quest', id: 63738 },
        { key: 'chainsofdomination-they-could-be-anyone', name: 'They Could Be Anyone', type: 'quest', id: 63763 },
        { key: 'chainsofdomination-reliquary-restoration', name: 'Reliquary Restoration', type: 'achievement', id: 15066 },

        { key: 'reputation', name: 'Reputation', type: 'header', level: 0 },
        { key: 'reputation-ascended', type: 'reputation', name: 'The Ascended', id: 2407, max: 6 },
        { key: 'reputation-undyingarmy', type: 'reputation', name: 'The Undying Army', id: 2410, max: 6 },
        { key: 'reputation-wildhunt', type: 'reputation', name: 'The Wild Hunt', id: 2465, max: 6 },
        { key: 'reputation-courtofharvesters', type: 'reputation', name: 'Court of Harvesters', id: 2413, max: 6 },
        { key: 'reputation-venari', type: 'reputation', name: 'Ve\'nari', id: 2432, max: 4 },
        { key: 'reputation-deaths-advance', type: 'reputation', name: 'Death\'s Advance', id: 2470, max: 6 },
        { key: 'reputation-archivists-codex', type: 'reputation', name: 'The Archivists Codex', id: 2472, max: 3 },

        { key: 'professions', name: 'Professions', type: 'header', level: 0 },

        { key: 'professions-herbalism', type: 'profession-primary', name: 'Shadowlands Herbalism', id: 2760 },
        { key: 'professions-mining', type: 'profession-primary', name: 'Shadowlands Mining', id: 2761 },
        { key: 'professions-skinning', type: 'profession-primary', name: 'Shadowlands Skinning', id: 2762 },
        { key: 'professions-tailoring', type: 'profession-primary', name: 'Shadowlands Tailoring', id: 2759 },
        { key: 'professions-enchanting', type: 'profession-primary', name: 'Shadowlands Enchanting', id: 2753 },
        { key: 'professions-engineering', type: 'profession-primary', name: 'Shadowlands Engineering', id: 2755 },
        { key: 'professions-inscription', type: 'profession-primary', name: 'Shadowlands Inscription', id: 2756 },
        { key: 'professions-alchemy', type: 'profession-primary', name: 'Shadowlands Alchemy', id: 2750 },
        { key: 'professions-jewelcrafting', type: 'profession-primary', name: 'Shadowlands Jewelcrafting', id: 2757 },
        { key: 'professions-leatherworking', type: 'profession-primary', name: 'Shadowlands Leatherworking', id: 2758 },
        { key: 'professions-blacksmithing', type: 'profession-primary', name: 'Shadowlands Blacksmithing', id: 2751 },

        { key: 'professions-cooking', type: 'profession-secondary', name: 'Shadowlands Cooking', id: 2752 },
        { key: 'professions-fishing', type: 'profession-secondary', name: 'Shadowlands Fishing', id: 2754 },

        { key: 'sanctum', name: 'Covenant Sanctum', type: 'header', level: 0 },
        { key: 'sanctum-talents', name: 'Sanctum Improvements', type: 'header', level: 1 },
        { key: 'sanctum-travelnetwork', name: 'Travel Network', type: 'sanctum-talent', talentName: 'transport' },
        { key: 'sanctum-animaconductor', name: 'Anima Conductor', type: 'sanctum-talent', talentName: 'conductor' },
        { key: 'sanctum-adventures', name: 'Mission Table', type: 'sanctum-talent', talentName: 'missions' },
        { key: 'sanctum-special-kyrian', name: 'Path of Ascension', type: 'sanctum-talent', talentName: 'special', covenant: 'Kyrian' },
        { key: 'sanctum-special-necrolord', name: 'Abomination Factory', type: 'sanctum-talent', talentName: 'special', covenant: 'Necrolord' },
        { key: 'sanctum-special-nightfae', name: 'Queen\'s Conservatory', type: 'sanctum-talent', talentName: 'special', covenant: 'Night Fae' },
        { key: 'sanctum-special-venthyr', name: 'The Ember Court', type: 'sanctum-talent', talentName: 'special', covenant: 'Venthyr' },

        { key: 'sanctum-followers', name: 'Followers', type: 'header', level: 1 },
        { key: 'sanctum-follower-kyrian-kleia', name: 'Kleia', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-pelagos', name: 'Pelagos', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-mikanikos', name: 'Mikanikos', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-apolon', name: 'Apolon', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-auric', name: 'Auric Spiritguide', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-bron', name: 'Bron', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-clora', name: 'Clora', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-cromas', name: 'Cromas the Mystic', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-kosmas', name: 'Disciple Kosmas', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-elgu', name: 'ELGU - 007', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-hala', name: 'Hala', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-hermestes', name: 'Hermestes', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-ispiron', name: 'Ispiron', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-kiaranyka', name: 'Kiaranyka', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-kythekios', name: 'Kythekios', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-molako', name: 'Molako', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-pelodis-nemea', name: 'Pelodis or Nemea', type: 'sanctum-follower-any', covenant: 'Kyrian', followers: [ 'Pelodis', 'Nemea' ]},
        { key: 'sanctum-follower-kyrian-sika', name: 'Sika', type: 'sanctum-follower', covenant: 'Kyrian' },
        { key: 'sanctum-follower-kyrian-telethakas', name: 'Telethakas', type: 'sanctum-follower', covenant: 'Kyrian' },
        { key: 'sanctum-follower-kyrian-teliah', name: 'Teliah', type: 'sanctum-follower', covenant: 'Kyrian' },

        { key: 'sanctum-follower-necrolord-marileth', name: 'Plague Deviser Marileth', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-emeni', name: 'Emeni', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-heirmir', name: 'Bonesmith Heirmir', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-ashraka', name: 'Ashraka', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-xertora', name: 'Assembler Xertora', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-deathfang', name: 'Deathfang', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-enceladus', name: 'Enceladus', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-gorgelimb', name: 'Gorgelimb', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-gunn', name: 'Gunn Gorgebone', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-khaliiq', name: 'Khaliiq', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-kinessa', name: 'Kinessa the Absorbent', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-lyra', name: 'Lyra Hailstorm', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-plaguey', name: 'Plaguey', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-rathan', name: 'Rathan', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-rattlebag', name: 'Rattlebag', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-rencissa', name: 'Rencissa the Dynamo', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-ruyja', name: 'Ruyja Shockfist', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-mevix', name: 'Secutor Mevix', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-talethi', name: 'Talethi', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-velkein', name: 'Theotar', type: 'sanctum-follower', covenant: 'Necrolord' },

        { key: 'sanctum-follower-nightfae-niya', name: 'Niya', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-dreamweaver', name: 'Dreamweaver', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-korayn', name: 'Hunt-Captain Korayn', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-blisswing', name: 'Blisswing', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-chalkyth', name: 'Chalkyth', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-duskleaf', name: 'Duskleaf', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-ella', name: 'Ella', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-elwyn', name: 'Elwyn', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-groonoomcrooek', name: 'Groonoomcrooek', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-karynm', name: 'Guardian Kota', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-karynmwylyann', name: 'Karynmwylyann', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-llothwellyn', name: 'Lloth\'wellyn', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-shalor', name: 'Master Sha\'lor', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-qadarin', name: 'Qadarin', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-marasmius', name: 'Spore of Marasmius', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-sulanoom', name: 'Sulanoom', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-tezan', name: 'Te\'zan', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-vesperbloom', name: 'Watcher Vesperbloom', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-yanlar', name: 'Yanlar', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-yiralya', name: 'Yira\'lya', type: 'sanctum-follower', covenant: 'Night Fae' },

        { key: 'sanctum-follower-venthyr-nadjia', name: 'Nadjia the Mistblade', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-theotar', name: 'Theotar', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-draven', name: 'General Draven', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-ayeleth', name: 'Ayeleth', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-bogdan', name: 'Bogdan', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-chachi', name: 'Chachi the Artiste', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-dug', name: 'Dug Gravewell', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-kaletar', name: 'Kaletar', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-lassik', name: 'Lassik Spinebender', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-sybille', name: 'Lost Sybille', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-lucia', name: 'Lucia', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-iza', name: 'Madame Iza', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-nerith', name: 'Nerith Darkwing', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-rahel', name: 'Rahel', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-simone', name: 'Simone', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-steadyhands', name: 'Steadyhands', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-stonehead', name: 'Stonehead', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-stonehuck', name: 'Stonehuck', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-thela', name: 'Thela Soulsipper', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-vulca', name: 'Vulca', type: 'sanctum-follower', covenant: 'Venthyr' },

        // { key: 'sanctum-follower-general-ben-howell', name: 'Ben Howell', type: 'sanctum-follower' },
        { key: 'sanctum-follower-general-croman', name: 'Croman', type: 'sanctum-follower' },
        { key: 'sanctum-follower-general-meatball', name: 'Meatball', type: 'sanctum-follower' },
    ],
};

export {
    data,
};
