// tslint:disable:max-line-length
import { Checklist } from '../checklist.interface';

const data: Checklist = {
    id: 'sl-horde',
    items: [
        { key: 'leveling', name: 'Leveling', type: 'header', level: 0 },

        { key: 'leveling-bastion', name: 'Bastion', type: 'header', level: 1 },
        { key: 'leveling-bastion-mainquests', name: 'The Path to Ascension', type: 'achievement', id: 14281 },
        { key: 'leveling-bastion-sidequests', name: 'Sojourner of Bastion', type: 'achievement', id: 14801 },
        { key: 'leveling-bastion-dungeon', name: 'Necrotic Wake', type: 'quest', id: 60057 },

        { key: 'leveling-maldraxxus', name: 'Maldraxxus', type: 'header', level: 1 },
        { key: 'leveling-maldraxxus-mainquests', name: 'Blade of the Primus', type: 'achievement', id: 14206 },
        { key: 'leveling-maldraxxus-sidequests', name: 'Sojourner of Maldraxxus', type: 'achievement', id: 14799 },
        { key: 'leveling-maldraxxus-dungeon', name: 'Plaguefall', type: 'quest', id: 59520 },

        { key: 'leveling-ardenweald', name: 'Ardenweald', type: 'header', level: 1 },
        { key: 'leveling-ardenweald-mainquests', name: 'Awaken, Ardenweald', type: 'achievement', id: 14164 },
        { key: 'leveling-ardenweald-sidequests', name: 'Sojourner of Ardenweald', type: 'achievement', id: 14800 },
        { key: 'leveling-ardenweald-dungeon', name: 'Tirna Scithe', type: 'quest', id: 62371 },

        { key: 'leveling-revendreth', name: 'Revendreth', type: 'header', level: 1 },
        { key: 'leveling-revendreth-mainquests', name: 'The Master of Revendreth', type: 'achievement', id: 13878 },
        { key: 'leveling-revendreth-sidequests', name: 'Sojourner of Revendreth', type: 'achievement', id: 14798 },
        { key: 'leveling-revendreth-dungeon', name: 'Halls of Atonement', type: 'quest', id: 58092 },

        { key: 'leveling-general', name: 'General', type: 'header', level: 1 },
        { key: 'leveling-general-50', name: 'Level 50', type: 'level', max: 50 },
        { key: 'leveling-general-60', name: 'Level 60', type: 'level', max: 60 },

        { key: 'leveling-gear', name: 'Gear', type: 'header', level: 1 },
        { key: 'leveling-gear-158', name: 'Item Level 158 / Superior', type: 'avg-item-level', max: 158 },

        { key: 'campaign', name: 'Covenant Campaign', type: 'header', level: 0 },
        { key: 'campaign-choosingyourpurpose', name: 'Choosing Your Purpose', type: 'achievement', id: 14627 },
        { key: 'campaign-renown10', name: 'Renown 10', type: 'renown', threshold: 10 },
        { key: 'campaign-renown20', name: 'Renown 20', type: 'renown', threshold: 20 },
        { key: 'campaign-renown30', name: 'Renown 30', type: 'renown', threshold: 30 },
        { key: 'campaign-renown40', name: 'Renown 40', type: 'renown', threshold: 40 },
        { key: 'campaign-torghast', name: 'The Captive King', type: 'quest', id: 61730 },
        { key: 'campaign-finished-kyrian', name: 'Covenant Campaign', covenant: 'Kyrian', type: 'quest', id: 62557 },
        { key: 'campaign-finished-necrolords', name: 'Covenant Campaign', covenant: 'Necrolord', type: 'quest', id: 62406 },
        { key: 'campaign-finished-nightfae', name: 'Covenant Campaign', covenant: 'Night Fae', type: 'quest', id: 60108 },
        { key: 'campaign-finished-venthyr', name: 'Covenant Campaign', covenant: 'Venthyr', type: 'quest', id: 58407 },
        
        { key: 'chainsofdomination', name: 'Chains of Domination', type: 'header', level: 0 },
        { key: 'chainsofdomination-renown-50', name: 'Renown 50', type: 'renown', threshold: 50 },
        { key: 'chainsofdomination-renown-60', name: 'Renown 60', type: 'renown', threshold: 60 },
        { key: 'chainsofdomination-renown-70', name: 'Renown 70', type: 'renown', threshold: 70 },
        { key: 'chainsofdomination-renown-80', name: 'Renown 80', type: 'renown', threshold: 80 },
        { key: 'chainsofdomination-story', name: 'Chains of Domination', type: 'achievement', id: 14961 },
        { key: 'chainsofdomination-boxofmanythings', name: 'Box of Many Things', type: 'quest', id: 64216 },
        { key: 'chainsofdomination-tazavesh-intro', name: 'The Veiled Market', type: 'quest', id: 63985 },
        { key: 'chainsofdomination-establishing-the-archive', name: 'Establishing the Archive', type: 'quest', id: 63738 },
        { key: 'chainsofdomination-they-could-be-anyone', name: 'They Could Be Anyone', type: 'quest', id: 63763 },
        { key: 'chainsofdomination-reliquary-restoration', name: 'Reliquary Restoration', type: 'achievement', id: 15066 },

        { key: 'reputation', name: 'Reputation', type: 'header', level: 0 },
        { key: 'reputation-ascended', type: 'reputation', name: 'The Ascended', id: 2407, max: 6 },
        { key: 'reputation-undyingarmy', type: 'reputation', name: 'The Undying Army', id: 2410, max: 6 },
        { key: 'reputation-wildhunt', type: 'reputation', name: 'The Wild Hunt', id: 2465, max: 6 },
        { key: 'reputation-courtofharvesters', type: 'reputation', name: 'Court of Harvesters', id: 2413, max: 6 },
        { key: 'reputation-venari', type: 'reputation', name: 'Ve\'nari', id: 2432, max: 4 },
        { key: 'reputation-deaths-advance', type: 'reputation', name: 'Death\'s Advance', id: 2470, max: 6 },
        { key: 'reputation-archivists-codex', type: 'reputation', name: 'The Archivists Codex', id: 2472, max: 3 },

        { key: 'professions', name: 'Professions', type: 'header', level: 0 },

        { key: 'professions-herbalism', type: 'profession-primary', name: 'Shadowlands Herbalism', id: 2760 },
        { key: 'professions-mining', type: 'profession-primary', name: 'Shadowlands Mining', id: 2761 },
        { key: 'professions-skinning', type: 'profession-primary', name: 'Shadowlands Skinning', id: 2762 },
        { key: 'professions-tailoring', type: 'profession-primary', name: 'Shadowlands Tailoring', id: 2759 },
        { key: 'professions-enchanting', type: 'profession-primary', name: 'Shadowlands Enchanting', id: 2753 },
        { key: 'professions-engineering', type: 'profession-primary', name: 'Shadowlands Engineering', id: 2755 },
        { key: 'professions-inscription', type: 'profession-primary', name: 'Shadowlands Inscription', id: 2756 },
        { key: 'professions-alchemy', type: 'profession-primary', name: 'Shadowlands Alchemy', id: 2750 },
        { key: 'professions-jewelcrafting', type: 'profession-primary', name: 'Shadowlands Jewelcrafting', id: 2757 },
        { key: 'professions-leatherworking', type: 'profession-primary', name: 'Shadowlands Leatherworking', id: 2758 },
        { key: 'professions-blacksmithing', type: 'profession-primary', name: 'Shadowlands Blacksmithing', id: 2751 },

        { key: 'professions-cooking', type: 'profession-secondary', name: 'Shadowlands Cooking', id: 2752 },
        { key: 'professions-fishing', type: 'profession-secondary', name: 'Shadowlands Fishing', id: 2754 },

        { key: 'sanctum', name: 'Covenant Sanctum', type: 'header', level: 0 },
        { key: 'sanctum-travelnetwork', name: 'Master Navigator', type: 'achievement', id: 14633 },
        { key: 'sanctum-animaconductor', name: 'Conducting Anima', type: 'achievement', id: 14632 },
        { key: 'sanctum-adventures', name: 'Adventurer in Chief', type: 'achievement', id: 14636 },
        { key: 'sanctum-special', name: 'Your Covenant\'s Favor', type: 'manual' },

        { key: 'sanctum-follower-kyrian-kleia', name: 'Follower: Kleia', type: 'quest', covenant: 'Kyrian', id: 58797 },
        { key: 'sanctum-follower-kyrian-pelagos', name: 'Follower: Pelagos', type: 'quest', covenant: 'Kyrian', id: 57898 },
        { key: 'sanctum-follower-kyrian-mikanikos', name: 'Follower: Mikanikos', type: 'quest', covenant: 'Kyrian', id: 59919 },
        { key: 'sanctum-follower-kyrian-apolon', name: 'Follower: Apolon', type: 'quest', covenant: 'Kyrian', id: 61863 },
        { key: 'sanctum-follower-kyrian-auric', name: 'Follower: Auric Spiritguide', type: 'quest', covenant: 'Kyrian', id: 64463 },
        { key: 'sanctum-follower-kyrian-bron', name: 'Follower: Bron', type: 'quest', covenant: 'Kyrian', id: 61864 },
        { key: 'sanctum-follower-kyrian-clora', name: 'Follower: Clora', type: 'quest', covenant: 'Kyrian', id: 61862 },
        { key: 'sanctum-follower-kyrian-cromas', name: 'Follower: Cromas the Mystic', type: 'quest', covenant: 'Kyrian', id: 64462 },
        { key: 'sanctum-follower-kyrian-kosmas', name: 'Follower: Disciple Kosmas', type: 'quest', covenant: 'Kyrian', id: 61865 },
        { key: 'sanctum-follower-kyrian-elgu', name: 'Follower: ELGU-007', type: 'quest', covenant: 'Kyrian', id: 64170 },
        { key: 'sanctum-follower-kyrian-hala', name: 'Follower: Hala', type: 'quest', covenant: 'Kyrian', id: 61319 },
        { key: 'sanctum-follower-kyrian-hermestes', name: 'Follower: Hermestes', type: 'quest', covenant: 'Kyrian', id: 64461 },
        { key: 'sanctum-follower-kyrian-ispiron', name: 'Follower: Ispiron', type: 'quest', covenant: 'Kyrian', id: 61321 },
        { key: 'sanctum-follower-kyrian-kiaranyka', name: 'Follower: Kiaranyka', type: 'quest', covenant: 'Kyrian', id: 64171 },
        { key: 'sanctum-follower-kyrian-kythekios', name: 'Follower: Kythekios', type: 'quest', covenant: 'Kyrian', id: 61313 },
        { key: 'sanctum-follower-kyrian-molako', name: 'Follower: Molako', type: 'quest', covenant: 'Kyrian', id: 61320 },
        { key: 'sanctum-follower-kyrian-pelodis-nemea', name: 'Follower: Pelodis or Nemea', type: 'any-quest', covenant: 'Kyrian', quests: [
            { id: 61860, name: 'Pelodis' },
            { id: 61859, name: 'Nemea' },
        ]},
        { key: 'sanctum-follower-kyrian-sika', name: 'Follower: Sika', type: 'quest', covenant: 'Kyrian', id: 61861 },
        { key: 'sanctum-follower-kyrian-telethakas', name: 'Follower: Telethakas', type: 'quest', covenant: 'Kyrian', id: 61318 },
        { key: 'sanctum-follower-kyrian-teliah', name: 'Follower: Teliah', type: 'quest', covenant: 'Kyrian', id: 61317 },

        { key: 'sanctum-follower-necrolord-marileth', name: 'Follower: Plague Deviser Marileth', type: 'quest', covenant: 'Necrolord', id: 59597 },
        { key: 'sanctum-follower-necrolord-emeni', name: 'Follower: Emeni', type: 'quest', covenant: 'Necrolord', id: 60110 },
        { key: 'sanctum-follower-necrolord-heirmir', name: 'Follower: Bonesmith Heirmir', type: 'quest', covenant: 'Necrolord', id: 60111 },
        { key: 'sanctum-follower-necrolord-ashraka', name: 'Follower: Ashraka', type: 'quest', covenant: 'Necrolord', id: 61957 },
        { key: 'sanctum-follower-necrolord-xertora', name: 'Follower: Assembler Xertora', type: 'quest', covenant: 'Necrolord', id: 61960 },
        { key: 'sanctum-follower-necrolord-deathfang', name: 'Follower: Deathfang', type: 'quest', covenant: 'Necrolord', id: 64466 },
        { key: 'sanctum-follower-necrolord-enceladus', name: 'Follower: Enceladus', type: 'quest', covenant: 'Necrolord', id: 64465 },
        { key: 'sanctum-follower-necrolord-gorgelimb', name: 'Follower: Gorgelimb', type: 'quest', covenant: 'Necrolord', id: 61958 },
        { key: 'sanctum-follower-necrolord-gunn', name: 'Follower: Gunn Gorgebone', type: 'quest', covenant: 'Necrolord', id: 62312 },
        { key: 'sanctum-follower-necrolord-khaliiq', name: 'Follower: Khaliiq', type: 'quest', covenant: 'Necrolord', id: 62314 },
        { key: 'sanctum-follower-necrolord-kinessa', name: 'Follower: Kinessa the Absorbent', type: 'quest', covenant: 'Necrolord', id: 64173 },
        { key: 'sanctum-follower-necrolord-lyra', name: 'Follower: Lyra Hailstorm', type: 'quest', covenant: 'Necrolord', id: 64464 },
        { key: 'sanctum-follower-necrolord-plaguey', name: 'Follower: Plaguey', type: 'quest', covenant: 'Necrolord', id: 62315 },
        { key: 'sanctum-follower-necrolord-rathan', name: 'Follower: Rathan', type: 'quest', covenant: 'Necrolord', id: 62316 },
        { key: 'sanctum-follower-necrolord-rattlebag', name: 'Follower: Rattlebag', type: 'quest', covenant: 'Necrolord', id: 61961 },
        { key: 'sanctum-follower-necrolord-rencissa', name: 'Follower: Rencissa the Dynamo', type: 'quest', covenant: 'Necrolord', id: 62313 },
        { key: 'sanctum-follower-necrolord-ruyja', name: 'Follower: Ruyja Shockfist', type: 'quest', covenant: 'Necrolord', id: 64172 },
        { key: 'sanctum-follower-necrolord-mevix', name: 'Follower: Secutor Mevix', type: 'quest', covenant: 'Necrolord', id: 62309 },
        { key: 'sanctum-follower-necrolord-talethi', name: 'Follower: Talethi', type: 'quest', covenant: 'Necrolord', id: 61959 },
        { key: 'sanctum-follower-necrolord-velkein', name: 'Follower: Theotar', type: 'quest', covenant: 'Necrolord', id: 61962 },

        { key: 'sanctum-follower-nightfae-niya', name: 'Follower: Niya', type: 'quest', covenant: 'Night Fae', id: 61542 },
        { key: 'sanctum-follower-nightfae-dreamweaver', name: 'Follower: Dreamweaver', type: 'quest', covenant: 'Night Fae', id: 61058 },
        { key: 'sanctum-follower-nightfae-korayn', name: 'Follower: Hunt-Captain Korayn', type: 'quest', covenant: 'Night Fae', id: 61057 },
        { key: 'sanctum-follower-nightfae-blisswing', name: 'Follower: Blisswing', type: 'quest', covenant: 'Night Fae', id: 61421 },
        { key: 'sanctum-follower-nightfae-chalkyth', name: 'Follower: Chalkyth', type: 'quest', covenant: 'Night Fae', id: 61424 },
        { key: 'sanctum-follower-nightfae-duskleaf', name: 'Follower: Duskleaf', type: 'quest', covenant: 'Night Fae', id: 61422 },
        { key: 'sanctum-follower-nightfae-ella', name: 'Follower: Ella', type: 'quest', covenant: 'Night Fae', id: 64169 },
        { key: 'sanctum-follower-nightfae-elwyn', name: 'Follower: Elwyn', type: 'quest', covenant: 'Night Fae', id: 64459 },
        { key: 'sanctum-follower-nightfae-groonoomcrooek', name: 'Follower: Groonoomcrooek', type: 'quest', covenant: 'Night Fae', id: 61857 },
        { key: 'sanctum-follower-nightfae-karynm', name: 'Follower: Guardian Kota', type: 'quest', covenant: 'Night Fae', id: 61852 },
        { key: 'sanctum-follower-nightfae-karynmwylyann', name: 'Follower: Karynmwylyann', type: 'quest', covenant: 'Night Fae', id: 61423 },
        { key: 'sanctum-follower-nightfae-llothwellyn', name: 'Follower: Lloth\'wellyn', type: 'quest', covenant: 'Night Fae', id: 61425 },
        { key: 'sanctum-follower-nightfae-shalor', name: 'Follower: Master Sha\'lor', type: 'quest', covenant: 'Night Fae', id: 61854 },
        { key: 'sanctum-follower-nightfae-qadarin', name: 'Follower: Qadarin', type: 'quest', covenant: 'Night Fae', id: 61855 },
        { key: 'sanctum-follower-nightfae-marasmius', name: 'Follower: Spore of Marasmius', type: 'quest', covenant: 'Night Fae', id: 64168 },
        { key: 'sanctum-follower-nightfae-sulanoom', name: 'Follower: Sulanoom', type: 'quest', covenant: 'Night Fae', id: 64458 },
        { key: 'sanctum-follower-nightfae-tezan', name: 'Follower: Te\'zan', type: 'quest', covenant: 'Night Fae', id: 61853 },
        { key: 'sanctum-follower-nightfae-vesperbloom', name: 'Follower: Watcher Vesperbloom', type: 'quest', covenant: 'Night Fae', id: 61856 },
        { key: 'sanctum-follower-nightfae-yanlar', name: 'Follower: Yanlar', type: 'quest', covenant: 'Night Fae', id: 64460 },
        { key: 'sanctum-follower-nightfae-yiralya', name: 'Follower: Yira\'lya', type: 'quest', covenant: 'Night Fae', id: 61426 },

        { key: 'sanctum-follower-venthyr-nadjia', name: 'Follower: Nadjia the Mistblade', type: 'quest', covenant: 'Venthyr', id: 62918 },
        { key: 'sanctum-follower-venthyr-theotar', name: 'Follower: Theotar', type: 'quest', covenant: 'Venthyr', id: 59343 },
        { key: 'sanctum-follower-venthyr-draven', name: 'Follower: General Draven', type: 'quest', covenant: 'Venthyr', id: 59325 },
        { key: 'sanctum-follower-venthyr-ayeleth', name: 'Follower: Ayeleth', type: 'quest', covenant: 'Venthyr', id: 61223 },
        { key: 'sanctum-follower-venthyr-bogdan', name: 'Follower: Bogdan', type: 'quest', covenant: 'Venthyr', id: 61792 },
        { key: 'sanctum-follower-venthyr-chachi', name: 'Follower: Chachi the Artiste', type: 'quest', covenant: 'Venthyr', id: 64467 },
        { key: 'sanctum-follower-venthyr-dug', name: 'Follower: Dug Gravewell', type: 'quest', covenant: 'Venthyr', id: 61218 },
        { key: 'sanctum-follower-venthyr-kaletar', name: 'Follower: Kaletar', type: 'quest', covenant: 'Venthyr', id: 61222 },
        { key: 'sanctum-follower-venthyr-lassik', name: 'Follower: Lassik Spinebender', type: 'quest', covenant: 'Venthyr', id: 64175 },
        { key: 'sanctum-follower-venthyr-sybille', name: 'Follower: Lost Sybille', type: 'quest', covenant: 'Venthyr', id: 61789 },
        { key: 'sanctum-follower-venthyr-lucia', name: 'Follower: Lucia', type: 'quest', covenant: 'Venthyr', id: 64469 },
        { key: 'sanctum-follower-venthyr-iza', name: 'Follower: Madame Iza', type: 'quest', covenant: 'Venthyr', id: 64468 },
        { key: 'sanctum-follower-venthyr-nerith', name: 'Follower: Nerith Darkwing', type: 'quest', covenant: 'Venthyr', id: 61219 },
        { key: 'sanctum-follower-venthyr-rahel', name: 'Follower: Rahel', type: 'quest', covenant: 'Venthyr', id: 61729 },
        { key: 'sanctum-follower-venthyr-simone', name: 'Follower: Simone', type: 'quest', covenant: 'Venthyr', id: 61788 },
        { key: 'sanctum-follower-venthyr-steadyhands', name: 'Follower: Steadyhands', type: 'quest', covenant: 'Venthyr', id: 64174 },
        { key: 'sanctum-follower-venthyr-stonehead', name: 'Follower: Stonehead', type: 'quest', covenant: 'Venthyr', id: 61786 },
        { key: 'sanctum-follower-venthyr-stonehuck', name: 'Follower: Stonehuck', type: 'quest', covenant: 'Venthyr', id: 61221 },
        { key: 'sanctum-follower-venthyr-thela', name: 'Follower: Thela Soulsipper', type: 'quest', covenant: 'Venthyr', id: 61217 },
        { key: 'sanctum-follower-venthyr-vulca', name: 'Follower: Vulca', type: 'quest', covenant: 'Venthyr', id: 61790 },

        // { key: 'sanctum-follower-general-ben-howell', name: 'Follower: Ben Howell', type: 'quest', id: 64654 },
        { key: 'sanctum-follower-general-croman', name: 'Follower: Croman', type: 'quest', id: 62999 },
        { key: 'sanctum-follower-general-meatball', name: 'Follower: Meatball', type: 'quest', id: 60651 },
    ],
};

export {
    data,
};
