// tslint:disable:max-line-length
import { Checklist } from '../checklist.interface';

const data: Checklist = {
    id: 'sl-horde',
    items: [
        { key: 'leveling', name: 'Leveling', type: 'header', level: 0 },

        { key: 'leveling-bastion', name: 'Bastion', type: 'header', level: 1 },
        { key: 'leveling-bastion-mainquests', name: 'The Path to Ascension', type: 'achievement', id: 14281 },
        { key: 'leveling-bastion-sidequests', name: 'Sojourner of Bastion', type: 'achievement', id: 14801 },
        { key: 'leveling-bastion-dungeon', name: 'Necrotic Wake', type: 'quest', id: 60057 },

        { key: 'leveling-maldraxxus', name: 'Maldraxxus', type: 'header', level: 1 },
        { key: 'leveling-maldraxxus-mainquests', name: 'Blade of the Primus', type: 'achievement', id: 14206 },
        { key: 'leveling-maldraxxus-sidequests', name: 'Sojourner of Maldraxxus', type: 'achievement', id: 14799 },
        { key: 'leveling-maldraxxus-dungeon', name: 'Plaguefall', type: 'quest', id: 59520 },

        { key: 'leveling-ardenweald', name: 'Ardenweald', type: 'header', level: 1 },
        { key: 'leveling-ardenweald-mainquests', name: 'Awaken, Ardenweald', type: 'achievement', id: 14164 },
        { key: 'leveling-ardenweald-sidequests', name: 'Sojourner of Ardenweald', type: 'achievement', id: 14800 },
        { key: 'leveling-ardenweald-dungeon', name: 'Tirna Scithe', type: 'quest', id: 62371 },

        { key: 'leveling-revendreth', name: 'Revendreth', type: 'header', level: 1 },
        { key: 'leveling-revendreth-mainquests', name: 'The Master of Revendreth', type: 'achievement', id: 13878 },
        { key: 'leveling-revendreth-sidequests', name: 'Sojourner of Revendreth', type: 'achievement', id: 14798 },
        { key: 'leveling-revendreth-dungeon', name: 'Halls of Atonement', type: 'quest', id: 58092 },

        { key: 'leveling-general', name: 'General', type: 'header', level: 1 },
        { key: 'leveling-general-50', name: 'Level 50', type: 'level', max: 50 },
        { key: 'leveling-general-60', name: 'Level 60', type: 'level', max: 60 },

        { key: 'leveling-gear', name: 'Gear', type: 'header', level: 1 },
        { key: 'leveling-gear-158', name: 'Item Level 158 / Superior', type: 'avg-item-level', max: 158 },

        { key: 'campaign', name: 'Covenant Campaign', type: 'header', level: 0 },
        { key: 'campaign-choosingyourpurpose', name: 'Choosing Your Purpose', type: 'achievement', id: 14627 },
        { key: 'campaign-renown10', name: 'Renown 10', type: 'renown', threshold: 10 },
        { key: 'campaign-renown20', name: 'Renown 20', type: 'renown', threshold: 20 },
        { key: 'campaign-renown30', name: 'Renown 30', type: 'renown', threshold: 30 },
        { key: 'campaign-renown40', name: 'Renown 40', type: 'renown', threshold: 40 },
        { key: 'campaign-torghast', name: 'The Captive King', type: 'quest', id: 61730 },
        { key: 'campaign-finished-kyrian', name: 'Covenant Campaign', covenant: 'Kyrian', type: 'quest', id: 62557 },
        { key: 'campaign-finished-necrolords', name: 'Covenant Campaign', covenant: 'Necrolord', type: 'quest', id: 62406 },
        { key: 'campaign-finished-nightfae', name: 'Covenant Campaign', covenant: 'Night Fae', type: 'quest', id: 60108 },
        { key: 'campaign-finished-venthyr', name: 'Covenant Campaign', covenant: 'Venthyr', type: 'quest', id: 58407 },
        
        { key: 'chainsofdomination', name: 'Chains of Domination', type: 'header', level: 0 },
        { key: 'chainsofdomination-renown-50', name: 'Renown 50', type: 'renown', threshold: 50 },
        { key: 'chainsofdomination-renown-60', name: 'Renown 60', type: 'renown', threshold: 60 },
        { key: 'chainsofdomination-renown-70', name: 'Renown 70', type: 'renown', threshold: 70 },
        { key: 'chainsofdomination-renown-80', name: 'Renown 80', type: 'renown', threshold: 80 },
        { key: 'chainsofdomination-story', name: 'Chains of Domination', type: 'achievement', id: 14961 },
        { key: 'chainsofdomination-boxofmanythings', name: 'Box of Many Things', type: 'quest', id: 64216 },
        { key: 'chainsofdomination-tazavesh-intro', name: 'The Veiled Market', type: 'quest', id: 63985 },
        { key: 'chainsofdomination-establishing-the-archive', name: 'Establishing the Archive', type: 'quest', id: 63738 },
        { key: 'chainsofdomination-they-could-be-anyone', name: 'They Could Be Anyone', type: 'quest', id: 63763 },
        { key: 'chainsofdomination-reliquary-restoration', name: 'Reliquary Restoration', type: 'achievement', id: 15066 },
        { key: 'chainsofdomination-a-unified-effort', name: 'A Unified Effort', type: 'quest', id: 64106 },

        { key: 'eternitysend', name: 'Eternity\'s End', type: 'header', level: 0 },
        { key: 'eternitysend-story', name: 'Eternity\'s End', type: 'achievement', id: 15259 },
        { key: 'eternitysend-epilogue', name: 'Epilogue - Judgement', type: 'quest', id: 65297 },
        { key: 'eternitysend-sidequests', name: 'Path to Enlightenment', type: 'achievement', id: 15515 },
        { key: 'eternitysend-cyphers', name: 'Cyphers of the First Ones', type: 'achievement', id: 15402 },
        { key: 'eternitysend-jirotohero', name: 'Jiro to Hero', type: 'quest', id: 65219 },
        { key: 'eternitysend-patientbufonid', name: 'The Patient Bufonid', type: 'quest', id: 65732 },
        { key: 'eternitysend-reapwhatwehavesown', name: 'Reap what we have sown', type: 'quest', id: 64648 },
        { key: 'eternitysend-protoform-pets', name: 'Protoform Synthesis - Pets', type: 'quest', id: 65419 },
        { key: 'eternitysend-protoform-mounts', name: 'Protoform Synthesis - Mounts', type: 'quest', id: 65427 },
        { key: 'eternitysend-jailersgauntlet', name: 'The Jailer\'s Gauntlet', type: 'quest', id: 65625 },

        { key: 'sl-epilogue', name : 'Shadowlands Epilogue', type: 'header', level: 0 },
        { key: 'sl-epilogue-silentvigil', name: 'Silent Vigil', type: 'quest', id: 66170 },
        { key: 'sl-epilogue-lordaeron', name: 'A Walk with Ghosts', type: 'quest', id: 65788 },
        { key: 'sl-epilogue-giftofhope', name: 'A Gift of Hope', type: 'quest', id: 66243 },

        { key: 'reputation', name: 'Reputation', type: 'header', level: 0 },
        { key: 'reputation-ascended', type: 'reputation', name: 'The Ascended', id: 2407, max: 6 },
        { key: 'reputation-undyingarmy', type: 'reputation', name: 'The Undying Army', id: 2410, max: 6 },
        { key: 'reputation-wildhunt', type: 'reputation', name: 'The Wild Hunt', id: 2465, max: 6 },
        { key: 'reputation-courtofharvesters', type: 'reputation', name: 'Court of Harvesters', id: 2413, max: 6 },
        { key: 'reputation-venari', type: 'reputation', name: 'Ve\'nari', id: 2432, max: 4 },
        { key: 'reputation-deaths-advance', type: 'reputation', name: 'Death\'s Advance', id: 2470, max: 6 },
        { key: 'reputation-archivists-codex', type: 'reputation', name: 'The Archivists Codex', id: 2472, max: 4 },
        { key: 'reputation-enlightened', type: 'reputation', name: 'The Enlightened', id: 2478, max: 6 },

        { key: 'professions', name: 'Professions', type: 'header', level: 0 },

        { key: 'professions-herbalism', type: 'profession-primary', name: 'Shadowlands Herbalism', id: 2760 },
        { key: 'professions-mining', type: 'profession-primary', name: 'Shadowlands Mining', id: 2761 },
        { key: 'professions-skinning', type: 'profession-primary', name: 'Shadowlands Skinning', id: 2762 },
        { key: 'professions-tailoring', type: 'profession-primary', name: 'Shadowlands Tailoring', id: 2759 },
        { key: 'professions-enchanting', type: 'profession-primary', name: 'Shadowlands Enchanting', id: 2753 },
        { key: 'professions-engineering', type: 'profession-primary', name: 'Shadowlands Engineering', id: 2755 },
        { key: 'professions-inscription', type: 'profession-primary', name: 'Shadowlands Inscription', id: 2756 },
        { key: 'professions-alchemy', type: 'profession-primary', name: 'Shadowlands Alchemy', id: 2750 },
        { key: 'professions-jewelcrafting', type: 'profession-primary', name: 'Shadowlands Jewelcrafting', id: 2757 },
        { key: 'professions-leatherworking', type: 'profession-primary', name: 'Shadowlands Leatherworking', id: 2758 },
        { key: 'professions-blacksmithing', type: 'profession-primary', name: 'Shadowlands Blacksmithing', id: 2751 },

        { key: 'professions-cooking', type: 'profession-secondary', name: 'Shadowlands Cooking', id: 2752 },
        { key: 'professions-fishing', type: 'profession-secondary', name: 'Shadowlands Fishing', id: 2754 },

        { key: 'sanctum', name: 'Covenant Sanctum', type: 'header', level: 0 },
        { key: 'sanctum-talents', name: 'Sanctum Improvements', type: 'header', level: 1 },
        { key: 'sanctum-travelnetwork', name: 'Travel Network', type: 'sanctum-talent', talentName: 'transport' },
        { key: 'sanctum-animaconductor', name: 'Anima Conductor', type: 'sanctum-talent', talentName: 'conductor' },
        { key: 'sanctum-adventures', name: 'Mission Table', type: 'sanctum-talent', talentName: 'missions' },
        { key: 'sanctum-special-kyrian', name: 'Path of Ascension', type: 'sanctum-talent', talentName: 'special', covenant: 'Kyrian' },
        { key: 'sanctum-special-necrolord', name: 'Abomination Factory', type: 'sanctum-talent', talentName: 'special', covenant: 'Necrolord' },
        { key: 'sanctum-special-nightfae', name: 'Queen\'s Conservatory', type: 'sanctum-talent', talentName: 'special', covenant: 'Night Fae' },
        { key: 'sanctum-special-venthyr', name: 'The Ember Court', type: 'sanctum-talent', talentName: 'special', covenant: 'Venthyr' },

        { key: 'sanctum-missions', name: 'Sanctum Campaign Progress', type: 'header', level: 1 },
        { key: 'sanctum-missions-count', name: 'Missions completed', type: 'sanctum-missions-count' },

        { key: 'sanctum-followers', name: 'Followers', type: 'header', level: 1 },
        { key: 'sanctum-follower-kyrian-kleia', name: 'Kleia', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-pelagos', name: 'Pelagos', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-mikanikos', name: 'Mikanikos', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-apolon', name: 'Apolon', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-auric', name: 'Auric Spiritguide', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-bron', name: 'Bron', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-clora', name: 'Clora', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-cromas', name: 'Cromas the Mystic', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-kosmas', name: 'Disciple Kosmas', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-elgu', name: 'ELGU - 007', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-hala', name: 'Hala', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-hermestes', name: 'Hermestes', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-ispiron', name: 'Ispiron', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-kiaranyka', name: 'Kiaranyka', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-kythekios', name: 'Kythekios', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-molako', name: 'Molako', type: 'sanctum-follower', covenant: 'Kyrian'},
        { key: 'sanctum-follower-kyrian-pelodis-nemea', name: 'Pelodis or Nemea', type: 'sanctum-follower-any', covenant: 'Kyrian', followers: [ 'Pelodis', 'Nemea' ]},
        { key: 'sanctum-follower-kyrian-sika', name: 'Sika', type: 'sanctum-follower', covenant: 'Kyrian' },
        { key: 'sanctum-follower-kyrian-telethakas', name: 'Telethakas', type: 'sanctum-follower', covenant: 'Kyrian' },
        { key: 'sanctum-follower-kyrian-teliah', name: 'Teliah', type: 'sanctum-follower', covenant: 'Kyrian' },

        { key: 'sanctum-follower-necrolord-marileth', name: 'Plague Deviser Marileth', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-emeni', name: 'Emeni', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-heirmir', name: 'Bonesmith Heirmir', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-ashraka', name: 'Ashraka', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-xertora', name: 'Assembler Xertora', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-deathfang', name: 'Deathfang', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-enceladus', name: 'Enceladus', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-gorgelimb', name: 'Gorgelimb', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-gunn', name: 'Gunn Gorgebone', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-khaliiq', name: 'Khaliiq', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-kinessa', name: 'Kinessa the Absorbent', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-lyra', name: 'Lyra Hailstorm', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-plaguey', name: 'Plaguey', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-rathan', name: 'Rathan', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-rattlebag', name: 'Rattlebag', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-rencissa', name: 'Rencissa the Dynamo', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-ryuyja', name: 'Ryuja Shockfist', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-mevix', name: 'Secutor Mevix', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-talethi', name: 'Talethi', type: 'sanctum-follower', covenant: 'Necrolord' },
        { key: 'sanctum-follower-necrolord-velkein', name: 'Velkein', type: 'sanctum-follower', covenant: 'Necrolord' },

        { key: 'sanctum-follower-nightfae-niya', name: 'Niya', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-dreamweaver', name: 'Dreamweaver', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-korayn', name: 'Hunt-Captain Korayn', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-blisswing', name: 'Blisswing', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-chalkyth', name: 'Chalkyth', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-duskleaf', name: 'Duskleaf', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-ella', name: 'Ella', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-elwyn', name: 'Elwyn', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-groonoomcrooek', name: 'Groonoomcrooek', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-karynm', name: 'Guardian Kota', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-karynmwylyann', name: 'Karynmwylyann', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-llothwellyn', name: 'Lloth\'wellyn', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-shalor', name: 'Master Sha\'lor', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-qadarin', name: 'Qadarin', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-marasmius', name: 'Spore of Marasmius', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-sulanoom', name: 'Sulanoom', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-tezan', name: 'Te\'zan', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-vesperbloom', name: 'Watcher Vesperbloom', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-yanlar', name: 'Yanlar', type: 'sanctum-follower', covenant: 'Night Fae' },
        { key: 'sanctum-follower-nightfae-yiralya', name: 'Yira\'lya', type: 'sanctum-follower', covenant: 'Night Fae' },

        { key: 'sanctum-follower-venthyr-nadjia', name: 'Nadjia the Mistblade', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-theotar', name: 'Theotar', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-draven', name: 'General Draven', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-ayeleth', name: 'Ayeleth', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-bogdan', name: 'Bogdan', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-chachi', name: 'Chachi the Artiste', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-dug', name: 'Dug Gravewell', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-kaletar', name: 'Kaletar', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-lassik', name: 'Lassik Spinebender', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-sybille', name: 'Lost Sybille', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-lucia', name: 'Lucia', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-iza', name: 'Madame Iza', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-nerith', name: 'Nerith Darkwing', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-rahel', name: 'Rahel', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-simone', name: 'Simone', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-steadyhands', name: 'Steadyhands', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-stonehead', name: 'Stonehead', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-stonehuck', name: 'Stonehuck', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-thela', name: 'Thela Soulsipper', type: 'sanctum-follower', covenant: 'Venthyr' },
        { key: 'sanctum-follower-venthyr-vulca', name: 'Vulca', type: 'sanctum-follower', covenant: 'Venthyr' },

        // { key: 'sanctum-follower-general-ben-howell', name: 'Ben Howell', type: 'sanctum-follower' },
        { key: 'sanctum-follower-general-croman', name: 'Croman', type: 'sanctum-follower' },
        { key: 'sanctum-follower-general-meatball', name: 'Meatball', type: 'sanctum-follower' },

        { key: 'sanctum-conduits', name: 'Conduits', type: 'header', level: 1 },
        { key: 'sanctum-conduit-284', name: 'Adaptive Armor Fragment', type: 'sanctum-conduit', conduitId: 284, classes: [ 'Death Knight', 'Demon Hunter', 'Druid', 'Monk', 'Paladin', 'Warrior' ] },
        { key: 'sanctum-conduit-283', name: 'Condensed Anima Sphere', type: 'sanctum-conduit', conduitId: 283 },
        { key: 'sanctum-conduit-123', name: 'Debilitating Malady', type: 'sanctum-conduit', conduitId: 123, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-80', name: 'Withering Plague', type: 'sanctum-conduit', conduitId: 80, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-86', name: 'Blood Bond', type: 'sanctum-conduit', conduitId: 86, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-121', name: 'Meat Shield', type: 'sanctum-conduit', conduitId: 121, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-79', name: 'Accelerated Cold', type: 'sanctum-conduit', conduitId: 79, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-83', name: 'Eradicating Blow', type: 'sanctum-conduit', conduitId: 83, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-91', name: 'Everfrost', type: 'sanctum-conduit', conduitId: 91, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-122', name: 'Unleashed Frenzy', type: 'sanctum-conduit', conduitId: 122, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-124', name: 'Convocation of the Dead', type: 'sanctum-conduit', conduitId: 124, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-89', name: 'Embrace Death', type: 'sanctum-conduit', conduitId: 89, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-65', name: 'Eternal Hunger', type: 'sanctum-conduit', conduitId: 65, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-125', name: 'Lingering Plague', type: 'sanctum-conduit', conduitId: 125, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-128', name: 'Proliferation', type: 'sanctum-conduit', conduitId: 128, covenant: 'Kyrian', classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-126', name: 'Impenetrable Gloom', type: 'sanctum-conduit', conduitId: 126, covenant: 'Venthyr', classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-127', name: 'Brutal Grasp', type: 'sanctum-conduit', conduitId: 127, covenant: 'Necrolord', classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-250', name: 'Withering Ground', type: 'sanctum-conduit', conduitId: 250, covenant: 'Night Fae', classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-88', name: 'Hardened Bones', type: 'sanctum-conduit', conduitId: 88, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-108', name: 'Insatiable Appetite', type: 'sanctum-conduit', conduitId: 108, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-74', name: 'Reinforced Shell', type: 'sanctum-conduit', conduitId: 74, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-68', name: 'Chilled Resilience', type: 'sanctum-conduit', conduitId: 68, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-99', name: 'Fleeting Wind', type: 'sanctum-conduit', conduitId: 99, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-70', name: 'Spirit Drain', type: 'sanctum-conduit', conduitId: 70, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-106', name: 'Unending Grip', type: 'sanctum-conduit', conduitId: 106, classes: [ 'Death Knight' ] },
        { key: 'sanctum-conduit-153', name: 'Growing Inferno', type: 'sanctum-conduit', conduitId: 153, classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-172', name: 'Soul Furnace', type: 'sanctum-conduit', conduitId: 172, classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-179', name: 'Demon Muzzle', type: 'sanctum-conduit', conduitId: 179, classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-180', name: 'Roaring Fire', type: 'sanctum-conduit', conduitId: 180, classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-151', name: 'Dancing with Fate', type: 'sanctum-conduit', conduitId: 151, classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-150', name: 'Relentless Onslaught', type: 'sanctum-conduit', conduitId: 150, classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-152', name: 'Serrated Glaive', type: 'sanctum-conduit', conduitId: 152, classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-187', name: 'Repeat Decree', type: 'sanctum-conduit', conduitId: 187, covenant: 'Kyrian', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-198', name: 'Increased Scrutiny', type: 'sanctum-conduit', conduitId: 198, covenant: 'Venthyr', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-200', name: 'Brooding Pool', type: 'sanctum-conduit', conduitId: 200, covenant: 'Necrolord', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-281', name: 'Unnatural Malice', type: 'sanctum-conduit', conduitId: 281, covenant: 'Night Fae', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-130', name: 'Fel Defender', type: 'sanctum-conduit', conduitId: 130, classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-132', name: 'Shattered Restoration', type: 'sanctum-conduit', conduitId: 132, classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-131', name: 'Viscous Ink', type: 'sanctum-conduit', conduitId: 131, classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-138', name: 'Demonic Parole', type: 'sanctum-conduit', conduitId: 138, classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-134', name: 'Felfire Haste', type: 'sanctum-conduit', conduitId: 134, classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-145', name: 'Lost in Darkness', type: 'sanctum-conduit', conduitId: 145, classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-135', name: 'Ravenous Consumption', type: 'sanctum-conduit', conduitId: 135, classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-conduit-263', name: 'Fury of the Skies', type: 'sanctum-conduit', conduitId: 263, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-262', name: 'Precise Alignment', type: 'sanctum-conduit', conduitId: 262, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-261', name: 'Stellar Inspiration', type: 'sanctum-conduit', conduitId: 261, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-264', name: 'Umbral Intensity', type: 'sanctum-conduit', conduitId: 264, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-268', name: 'Carnivorous Instinct', type: 'sanctum-conduit', conduitId: 268, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-266', name: 'Incessant Hunter', type: 'sanctum-conduit', conduitId: 266, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-267', name: 'Sudden Ambush', type: 'sanctum-conduit', conduitId: 267, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-265', name: 'Taste for Blood', type: 'sanctum-conduit', conduitId: 265, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-270', name: 'Savage Combatant', type: 'sanctum-conduit', conduitId: 270, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-269', name: 'Unchecked Aggression', type: 'sanctum-conduit', conduitId: 269, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-272', name: 'Layered Mane', type: 'sanctum-conduit', conduitId: 272, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-271', name: 'Well-Honed Instincts', type: 'sanctum-conduit', conduitId: 271, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-274', name: 'Flash of Clarity', type: 'sanctum-conduit', conduitId: 274, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-275', name: 'Floral Recycling', type: 'sanctum-conduit', conduitId: 275, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-276', name: 'Ready for Anything', type: 'sanctum-conduit', conduitId: 276, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-273', name: 'Unstoppable Growth', type: 'sanctum-conduit', conduitId: 273, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-277', name: 'Deep Allegiance', type: 'sanctum-conduit', conduitId: 277, covenant: 'Kyrian', classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-280', name: 'Endless Thirst', type: 'sanctum-conduit', conduitId: 280, covenant: 'Venthyr', classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-278', name: 'Evolved Swarm', type: 'sanctum-conduit', conduitId: 278, covenant: 'Necrolord', classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-279', name: 'Conflux of Elements', type: 'sanctum-conduit', conduitId: 279, covenant: 'Night Fae', classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-254', name: 'Tough as Bark', type: 'sanctum-conduit', conduitId: 254, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-255', name: 'Ursine Vigor', type: 'sanctum-conduit', conduitId: 255, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-256', name: 'Innate Resolve', type: 'sanctum-conduit', conduitId: 256, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-258', name: 'Born Anew', type: 'sanctum-conduit', conduitId: 258, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-259', name: 'Front of the Pack', type: 'sanctum-conduit', conduitId: 259, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-260', name: 'Born of the Wilds', type: 'sanctum-conduit', conduitId: 260, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-257', name: 'Tireless Pursuit', type: 'sanctum-conduit', conduitId: 257, classes: [ 'Druid' ] },
        { key: 'sanctum-conduit-253', name: 'Bloodletting', type: 'sanctum-conduit', conduitId: 253, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-223', name: 'Echoing Call', type: 'sanctum-conduit', conduitId: 223, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-183', name: 'Ferocious Appetite', type: 'sanctum-conduit', conduitId: 183, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-185', name: 'One With the Beast', type: 'sanctum-conduit', conduitId: 185, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-189', name: 'Brutal Projectiles', type: 'sanctum-conduit', conduitId: 189, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-192', name: 'Deadly Chain', type: 'sanctum-conduit', conduitId: 192, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-199', name: 'Powerful Precision', type: 'sanctum-conduit', conduitId: 199, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-188', name: 'Sharpshooter\'s Focus', type: 'sanctum-conduit', conduitId: 188, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-251', name: 'Deadly Tandem', type: 'sanctum-conduit', conduitId: 251, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-252', name: 'Flame Infusion', type: 'sanctum-conduit', conduitId: 252, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-226', name: 'Stinging Strike', type: 'sanctum-conduit', conduitId: 226, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-224', name: 'Strength of the Pack', type: 'sanctum-conduit', conduitId: 224, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-137', name: 'Enfeebled Mark', type: 'sanctum-conduit', conduitId: 137, covenant: 'Kyrian', classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-139', name: 'Empowered Release', type: 'sanctum-conduit', conduitId: 139, covenant: 'Venthyr', classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-143', name: 'Necrotic Barrage', type: 'sanctum-conduit', conduitId: 143, covenant: 'Necrolord', classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-140', name: 'Spirit Attunement', type: 'sanctum-conduit', conduitId: 140, covenant: 'Night Fae', classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-166', name: 'Harmony of the Tortollan', type: 'sanctum-conduit', conduitId: 166, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-157', name: 'Marksman\'s Advantage', type: 'sanctum-conduit', conduitId: 157, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-170', name: 'Rejuvenating Wind', type: 'sanctum-conduit', conduitId: 170, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-173', name: 'Resilience of the Hunter', type: 'sanctum-conduit', conduitId: 173, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-282', name: 'Ambuscade', type: 'sanctum-conduit', conduitId: 282, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-178', name: 'Cheetah\'s Vigor', type: 'sanctum-conduit', conduitId: 178, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-175', name: 'Reversal of Fortune', type: 'sanctum-conduit', conduitId: 175, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-181', name: 'Tactical Retreat', type: 'sanctum-conduit', conduitId: 181, classes: [ 'Hunter' ] },
        { key: 'sanctum-conduit-34', name: 'Arcane Prodigy', type: 'sanctum-conduit', conduitId: 34, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-55', name: 'Artifice of the Archmage', type: 'sanctum-conduit', conduitId: 55, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-51', name: 'Magi\'s Brand', type: 'sanctum-conduit', conduitId: 51, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-36', name: 'Nether Precision', type: 'sanctum-conduit', conduitId: 36, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-249', name: 'Controlled Destruction', type: 'sanctum-conduit', conduitId: 249, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-53', name: 'Flame Accretion', type: 'sanctum-conduit', conduitId: 53, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-30', name: 'Infernal Cascade', type: 'sanctum-conduit', conduitId: 30, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-32', name: 'Master Flame', type: 'sanctum-conduit', conduitId: 32, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-21', name: 'Ice Bite', type: 'sanctum-conduit', conduitId: 21, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-20', name: 'Icy Propulsion', type: 'sanctum-conduit', conduitId: 20, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-18', name: 'Shivering Core', type: 'sanctum-conduit', conduitId: 18, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-17', name: 'Unrelenting Cold', type: 'sanctum-conduit', conduitId: 17, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-40', name: 'Ire of the Ascended', type: 'sanctum-conduit', conduitId: 40, covenant: 'Kyrian', classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-43', name: 'Siphoned Malice', type: 'sanctum-conduit', conduitId: 43, covenant: 'Venthyr', classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-39', name: 'Gift of the Lich', type: 'sanctum-conduit', conduitId: 39, covenant: 'Necrolord', classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-38', name: 'Discipline of the Grove', type: 'sanctum-conduit', conduitId: 38, covenant: 'Night Fae', classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-45', name: 'Cryo-Freeze', type: 'sanctum-conduit', conduitId: 45, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-48', name: 'Diverted Energy', type: 'sanctum-conduit', conduitId: 48, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-61', name: 'Tempest Barrier', type: 'sanctum-conduit', conduitId: 61, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-26', name: 'Flow of Time', type: 'sanctum-conduit', conduitId: 26, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-58', name: 'Incantation of Swiftness', type: 'sanctum-conduit', conduitId: 58, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-29', name: 'Grounding Surge', type: 'sanctum-conduit', conduitId: 29, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-23', name: 'Winter\'s Protection', type: 'sanctum-conduit', conduitId: 23, classes: [ 'Mage' ] },
        { key: 'sanctum-conduit-46', name: 'Scalding Brew', type: 'sanctum-conduit', conduitId: 46, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-57', name: 'Walk with the Ox', type: 'sanctum-conduit', conduitId: 57, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-47', name: 'Celestial Effervescence', type: 'sanctum-conduit', conduitId: 47, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-56', name: 'Evasive Stride', type: 'sanctum-conduit', conduitId: 56, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-28', name: 'Jade Bond', type: 'sanctum-conduit', conduitId: 28, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-54', name: 'Nourishing Chi', type: 'sanctum-conduit', conduitId: 54, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-31', name: 'Resplendent Mist', type: 'sanctum-conduit', conduitId: 31, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-44', name: 'Rising Sun Revival', type: 'sanctum-conduit', conduitId: 44, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-19', name: 'Calculated Strikes', type: 'sanctum-conduit', conduitId: 19, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-22', name: 'Coordinated Offensive', type: 'sanctum-conduit', conduitId: 22, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-16', name: 'Inner Fury', type: 'sanctum-conduit', conduitId: 16, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-24', name: 'Xuen\'s Bond', type: 'sanctum-conduit', conduitId: 24, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-59', name: 'Strike with Clarity', type: 'sanctum-conduit', conduitId: 59, covenant: 'Kyrian', classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-62', name: 'Imbued Reflections', type: 'sanctum-conduit', conduitId: 62, covenant: 'Venthyr', classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-60', name: 'Bone Marrow Hops', type: 'sanctum-conduit', conduitId: 60, covenant: 'Necrolord', classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-63', name: 'Way of the Fae', type: 'sanctum-conduit', conduitId: 63, covenant: 'Night Fae', classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-33', name: 'Fortifying Ingredients', type: 'sanctum-conduit', conduitId: 33, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-25', name: 'Grounding Breath', type: 'sanctum-conduit', conduitId: 25, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-15', name: 'Harm Denial', type: 'sanctum-conduit', conduitId: 15, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-37', name: 'Dizzying Tumble', type: 'sanctum-conduit', conduitId: 37, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-35', name: 'Lingering Numbness', type: 'sanctum-conduit', conduitId: 35, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-41', name: 'Swift Transference', type: 'sanctum-conduit', conduitId: 41, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-42', name: 'Tumbling Technique', type: 'sanctum-conduit', conduitId: 42, classes: [ 'Monk' ] },
        { key: 'sanctum-conduit-177', name: 'Enkindled Spirit', type: 'sanctum-conduit', conduitId: 177, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-193', name: 'Focused Light', type: 'sanctum-conduit', conduitId: 193, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-184', name: 'Resplendent Light', type: 'sanctum-conduit', conduitId: 184, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-194', name: 'Untempered Dedication', type: 'sanctum-conduit', conduitId: 194, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-196', name: 'Punish the Guilty', type: 'sanctum-conduit', conduitId: 196, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-195', name: 'Vengeful Shock', type: 'sanctum-conduit', conduitId: 195, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-197', name: 'Resolute Defender', type: 'sanctum-conduit', conduitId: 197, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-209', name: 'Royal Decree', type: 'sanctum-conduit', conduitId: 209, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-164', name: 'Expurgation', type: 'sanctum-conduit', conduitId: 164, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-176', name: 'Templar\'s Vindication', type: 'sanctum-conduit', conduitId: 176, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-167', name: 'Truth\'s Wake', type: 'sanctum-conduit', conduitId: 167, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-182', name: 'Virtuous Command', type: 'sanctum-conduit', conduitId: 182, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-216', name: 'Ringing Clarity', type: 'sanctum-conduit', conduitId: 216, covenant: 'Kyrian', classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-215', name: 'Hallowed Discernment', type: 'sanctum-conduit', conduitId: 215, covenant: 'Venthyr', classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-213', name: 'Righteous Might', type: 'sanctum-conduit', conduitId: 213, covenant: 'Necrolord', classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-210', name: 'The Long Summer', type: 'sanctum-conduit', conduitId: 210, covenant: 'Night Fae', classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-129', name: 'Divine Call', type: 'sanctum-conduit', conduitId: 129, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-141', name: 'Golden Path', type: 'sanctum-conduit', conduitId: 141, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-133', name: 'Shielding Words', type: 'sanctum-conduit', conduitId: 133, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-163', name: 'Echoing Blessings', type: 'sanctum-conduit', conduitId: 163, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-159', name: 'Light\'s Barding', type: 'sanctum-conduit', conduitId: 159, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-142', name: 'Pure Concentration', type: 'sanctum-conduit', conduitId: 142, classes: [ 'Paladin' ] },
        { key: 'sanctum-conduit-161', name: 'Wrench Evil', type: 'sanctum-conduit', conduitId: 161, classes: [ 'Paladin' ]},
        { key: 'sanctum-conduit-77', name: 'Exaltation', type: 'sanctum-conduit', conduitId: 77, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-76', name: 'Pain Transformation', type: 'sanctum-conduit', conduitId: 76, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-75', name: 'Shining Radiance', type: 'sanctum-conduit', conduitId: 75, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-81', name: 'Swift Penitence', type: 'sanctum-conduit', conduitId: 81, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-82', name: 'Focused Mending', type: 'sanctum-conduit', conduitId: 82, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-116', name: 'Holy Oration', type: 'sanctum-conduit', conduitId: 116, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-78', name: 'Lasting Spirit', type: 'sanctum-conduit', conduitId: 78, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-84', name: 'Resonant Words', type: 'sanctum-conduit', conduitId: 84, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-115', name: 'Dissonant Echoes', type: 'sanctum-conduit', conduitId: 115, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-107', name: 'Haunting Apparitions', type: 'sanctum-conduit', conduitId: 107, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-113', name: 'Mind Devourer', type: 'sanctum-conduit', conduitId: 113, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-114', name: 'Rabid Shadows', type: 'sanctum-conduit', conduitId: 114, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-87', name: 'Courageous Ascension', type: 'sanctum-conduit', conduitId: 87, covenant: 'Kyrian', classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-105', name: 'Shattered Perceptions', type: 'sanctum-conduit', conduitId: 105, covenant: 'Venthyr', classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-90', name: 'Festering Transfusion', type: 'sanctum-conduit', conduitId: 90, covenant: 'Necrolord', classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-101', name: 'Fae Fermata', type: 'sanctum-conduit', conduitId: 101, covenant: 'Night Fae', classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-71', name: 'Charitable Soul', type: 'sanctum-conduit', conduitId: 71, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-72', name: 'Light\'s Inspiration', type: 'sanctum-conduit', conduitId: 72, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-66', name: 'Translucent Image', type: 'sanctum-conduit', conduitId: 66, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-69', name: 'Clear Mind', type: 'sanctum-conduit', conduitId: 69, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-85', name: 'Mental Recovery', type: 'sanctum-conduit', conduitId: 85, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-67', name: 'Move with Grace', type: 'sanctum-conduit', conduitId: 67, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-73', name: 'Power Unto Others', type: 'sanctum-conduit', conduitId: 73, classes: [ 'Priest' ] },
        { key: 'sanctum-conduit-240', name: 'Lethal Poisons', type: 'sanctum-conduit', conduitId: 240, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-239', name: 'Maim, Mangle', type: 'sanctum-conduit', conduitId: 239, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-237', name: 'Poisoned Katar', type: 'sanctum-conduit', conduitId: 237, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-238', name: 'Well-Placed Steel', type: 'sanctum-conduit', conduitId: 238, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-242', name: 'Ambidexterity', type: 'sanctum-conduit', conduitId: 242, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-244', name: 'Count the Odds', type: 'sanctum-conduit', conduitId: 244, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-243', name: 'Sleight of Hand', type: 'sanctum-conduit', conduitId: 243, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-241', name: 'Triple Threat', type: 'sanctum-conduit', conduitId: 241, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-245', name: 'Deeper Daggers', type: 'sanctum-conduit', conduitId: 245, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-248', name: 'Perforated Veins', type: 'sanctum-conduit', conduitId: 248, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-246', name: 'Planned Execution', type: 'sanctum-conduit', conduitId: 246, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-247', name: 'Stiletto Staccato', type: 'sanctum-conduit', conduitId: 247, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-225', name: 'Reverberation', type: 'sanctum-conduit', conduitId: 225, covenant: 'Kyrian', classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-229', name: 'Lashing Scars', type: 'sanctum-conduit', conduitId: 229, covenant: 'Venthyr', classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-227', name: 'Sudden Fractures', type: 'sanctum-conduit', conduitId: 227, covenant: 'Necrolord', classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-228', name: 'Septic Shock', type: 'sanctum-conduit', conduitId: 228, covenant: 'Night Fae', classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-232', name: 'Cloaked in Shadows', type: 'sanctum-conduit', conduitId: 232, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-230', name: 'Nimble Fingers', type: 'sanctum-conduit', conduitId: 230, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-231', name: 'Recuperator', type: 'sanctum-conduit', conduitId: 231, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-234', name: 'Fade to Nothing', type: 'sanctum-conduit', conduitId: 234, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-236', name: 'Prepared for All', type: 'sanctum-conduit', conduitId: 236, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-233', name: 'Quick Decisions', type: 'sanctum-conduit', conduitId: 233, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-235', name: 'Rushed Setup', type: 'sanctum-conduit', conduitId: 235, classes: [ 'Rogue' ] },
        { key: 'sanctum-conduit-104', name: 'Call of Flame', type: 'sanctum-conduit', conduitId: 104, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-102', name: 'High Voltage', type: 'sanctum-conduit', conduitId: 102, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-100', name: 'Pyroclastic Shock', type: 'sanctum-conduit', conduitId: 100, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-103', name: 'Shake the Foundations', type: 'sanctum-conduit', conduitId: 103, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-112', name: 'Chilled to the Core', type: 'sanctum-conduit', conduitId: 112, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-110', name: 'Focused Lightning', type: 'sanctum-conduit', conduitId: 110, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-111', name: 'Magma Fist', type: 'sanctum-conduit', conduitId: 111, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-109', name: 'Unruly Winds', type: 'sanctum-conduit', conduitId: 109, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-117', name: 'Embrace of Earth', type: 'sanctum-conduit', conduitId: 117, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-119', name: 'Heavy Rainfall', type: 'sanctum-conduit', conduitId: 119, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-120', name: 'Nature\'s Focus', type: 'sanctum-conduit', conduitId: 120, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-118', name: 'Swirling Currents', type: 'sanctum-conduit', conduitId: 118, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-146', name: 'Elysian Dirge', type: 'sanctum-conduit', conduitId: 146, covenant: 'Kyrian', classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-149', name: 'Lavish Harvest', type: 'sanctum-conduit', conduitId: 149, covenant: 'Venthyr', classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-147', name: 'Tumbling Waves', type: 'sanctum-conduit', conduitId: 147, covenant: 'Necrolord', classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-148', name: 'Essential Extraction', type: 'sanctum-conduit', conduitId: 148, covenant: 'Night Fae', classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-92', name: 'Astral Protection', type: 'sanctum-conduit', conduitId: 92, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-93', name: 'Refreshing Waters', type: 'sanctum-conduit', conduitId: 93, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-94', name: 'Vital Accretion', type: 'sanctum-conduit', conduitId: 94, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-97', name: 'Crippling Hex', type: 'sanctum-conduit', conduitId: 97, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-98', name: 'Spiritual Resonance', type: 'sanctum-conduit', conduitId: 98, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-95', name: 'Thunderous Paws', type: 'sanctum-conduit', conduitId: 95, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-96', name: 'Totemic Surge', type: 'sanctum-conduit', conduitId: 96, classes: [ 'Shaman' ] },
        { key: 'sanctum-conduit-203', name: 'Withering Bolt', type: 'sanctum-conduit', conduitId: 203, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-174', name: 'Corrupting Leer', type: 'sanctum-conduit', conduitId: 174, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-202', name: 'Focused Malignancy', type: 'sanctum-conduit', conduitId: 202, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-201', name: 'Rolling Agony', type: 'sanctum-conduit', conduitId: 201, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-204', name: 'Borne of Blood', type: 'sanctum-conduit', conduitId: 204, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-205', name: 'Carnivorous Stalkers', type: 'sanctum-conduit', conduitId: 205, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-207', name: 'Fel Commando', type: 'sanctum-conduit', conduitId: 207, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-206', name: 'Tyrant\'s Soul', type: 'sanctum-conduit', conduitId: 206, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-211', name: 'Ashen Remains', type: 'sanctum-conduit', conduitId: 211, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-212', name: 'Combusting Engine', type: 'sanctum-conduit', conduitId: 212, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-208', name: 'Duplicitous Havoc', type: 'sanctum-conduit', conduitId: 208, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-214', name: 'Infernal Brand', type: 'sanctum-conduit', conduitId: 214, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-217', name: 'Soul Tithe', type: 'sanctum-conduit', conduitId: 217, covenant: 'Kyrian', classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-219', name: 'Catastrophic Origin', type: 'sanctum-conduit', conduitId: 219, covenant: 'Venthyr', classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-218', name: 'Fatal Decimation', type: 'sanctum-conduit', conduitId: 218, covenant: 'Necrolord', classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-220', name: 'Soul Eater', type: 'sanctum-conduit', conduitId: 220, covenant: 'Night Fae', classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-162', name: 'Accrued Vitality', type: 'sanctum-conduit', conduitId: 162, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-222', name: 'Diabolic Bloodstone', type: 'sanctum-conduit', conduitId: 222, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-160', name: 'Resolute Barrier', type: 'sanctum-conduit', conduitId: 160, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-171', name: 'Demonic Momentum', type: 'sanctum-conduit', conduitId: 171, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-144', name: 'Fel Celerity', type: 'sanctum-conduit', conduitId: 144, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-168', name: 'Shade of Terror', type: 'sanctum-conduit', conduitId: 168, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-221', name: 'Kilrogg\'s Cunning', type: 'sanctum-conduit', conduitId: 221, classes: [ 'Warlock' ] },
        { key: 'sanctum-conduit-11', name: 'Ashen Juggernaut', type: 'sanctum-conduit', conduitId: 11, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-12', name: 'Crash the Ramparts', type: 'sanctum-conduit', conduitId: 12, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-14', name: 'Merciless Bonegrinder', type: 'sanctum-conduit', conduitId: 14, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-169', name: 'Mortal Combo', type: 'sanctum-conduit', conduitId: 169, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-50', name: 'Depths of Insanity', type: 'sanctum-conduit', conduitId: 50, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-52', name: 'Hack and Slash', type: 'sanctum-conduit', conduitId: 52, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-64', name: 'Vicious Contempt', type: 'sanctum-conduit', conduitId: 64, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-186', name: 'Show of Force', type: 'sanctum-conduit', conduitId: 186, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-49', name: 'Unnerving Focus', type: 'sanctum-conduit', conduitId: 49, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-10', name: 'Fueled by Violence', type: 'sanctum-conduit', conduitId: 10, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-154', name: 'Piercing Verdict', type: 'sanctum-conduit', conduitId: 154, covenant: 'Kyrian', classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-165', name: 'Harrowing Punishment', type: 'sanctum-conduit', conduitId: 165, covenant: 'Venthyr', classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-158', name: 'Veteran\'s Repute', type: 'sanctum-conduit', conduitId: 158, covenant: 'Necrolord', classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-190', name: 'Destructive Reverberations', type: 'sanctum-conduit', conduitId: 190, covenant: 'Night Fae', classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-27', name: 'Indelible Victory', type: 'sanctum-conduit', conduitId: 27, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-5', name: 'Stalwart Guardian', type: 'sanctum-conduit', conduitId: 5, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-7', name: 'Brutal Vitality', type: 'sanctum-conduit', conduitId: 7, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-13', name: 'Cacophonous Roar', type: 'sanctum-conduit', conduitId: 13, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-191', name: 'Disturb the Peace', type: 'sanctum-conduit', conduitId: 191, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-8', name: 'Inspiring Presence', type: 'sanctum-conduit', conduitId: 8, classes: [ 'Warrior' ] },
        { key: 'sanctum-conduit-9', name: 'Safeguard', type: 'sanctum-conduit', conduitId: 9, classes: [ 'Warrior' ] },

        { key: 'sanctum-legendaries', name: 'Runecarving Powers', type: 'header', level: 1 },
        { key: 'sanctum-legendaries-1', name: 'Echo of Eonar', type: 'sanctum-legendary' },
        { key: 'sanctum-legendaries-2', name: 'Judgment of the Arbiter', type: 'sanctum-legendary' },
        { key: 'sanctum-legendaries-3', name: 'Norgannon\'s Sagacity', type: 'sanctum-legendary' },
        { key: 'sanctum-legendaries-4', name: 'Sephuz\'s Proclamation', type: 'sanctum-legendary' },
        { key: 'sanctum-legendaries-5', name: 'Stable Phantasma Lure', type: 'sanctum-legendary' },
        { key: 'sanctum-legendaries-6', name: 'Third Eye of the Jailer', type: 'sanctum-legendary' },
        { key: 'sanctum-legendaries-7', name: 'Vitality Sacrifice', type: 'sanctum-legendary' },
        { key: 'sanctum-legendaries-8', name: 'Maw Rattle', type: 'sanctum-legendary' },
        { key: 'sanctum-legendaries-9', name: 'Superstrain', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-10', name: 'Phearomones', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-11', name: 'Death\'s Embrace', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-12', name: 'Grip of the Everlasting', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-13', name: 'Bryndaor\'s Might', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-14', name: 'Crimson Rune Weapon', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-15', name: 'Gorefiend\'s Domination', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-16', name: 'Vampiric Aura', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-17', name: 'Koltira\'s Favor', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-18', name: 'Biting Cold', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-19', name: 'Absolute Zero', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-20', name: 'Rage of the Frozen Champion', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-21', name: 'Reanimated Shambler', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-22', name: 'Frenzied Monstrosity', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-23', name: 'Death\'s Certainty', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-24', name: 'Deadliest Coil', type: 'sanctum-legendary', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-25', name: 'Final Sentence', type: 'sanctum-legendary', covenant: 'Kyrian', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-26', name: 'Rampant Transference', type: 'sanctum-legendary', covenant: 'Night Fae', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-27', name: 'Abomination\'s Frenzy', type: 'sanctum-legendary', covenant: 'Necrolord', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-28', name: 'Insatiable Hunger', type: 'sanctum-legendary', covenant: 'Venthyr', classes: [ 'Death Knight' ] },
        { key: 'sanctum-legendaries-29', name: 'Collective Anguish', type: 'sanctum-legendary', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-30', name: 'Burning Wound', type: 'sanctum-legendary', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-31', name: 'Darkglare Medallion', type: 'sanctum-legendary', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-32', name: 'Darkest Hour', type: 'sanctum-legendary', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-33', name: 'Darker Nature', type: 'sanctum-legendary', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-34', name: 'Chaos Theory', type: 'sanctum-legendary', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-35', name: 'Erratic Fel Core', type: 'sanctum-legendary', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-36', name: 'Fel Bombardment', type: 'sanctum-legendary', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-37', name: 'Spirit of the Darkness Flame', type: 'sanctum-legendary', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-38', name: 'Razelikh\'s Defilement', type: 'sanctum-legendary', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-39', name: 'Fel Flame Fortification', type: 'sanctum-legendary', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-40', name: 'Fiery Soul', type: 'sanctum-legendary', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-41', name: 'Blind Faith', type: 'sanctum-legendary', covenant: 'Kyrian', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-42', name: 'Blazing Slaughter', type: 'sanctum-legendary', covenant: 'Night Fae', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-43', name: 'Demonic Oath', type: 'sanctum-legendary', covenant: 'Necrolord', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-44', name: 'Agony Gaze', type: 'sanctum-legendary', covenant: 'Venthyr', classes: [ 'Demon Hunter' ] },
        { key: 'sanctum-legendaries-45', name: 'Draught of Deep Focus', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-46', name: 'Circle of Life and Death', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-47', name: 'Lycara\'s Fleeting Glimpse', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-48', name: 'Oath of the Elder Druid', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-49', name: 'Oneth\'s Clear Vision', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-50', name: 'Primordial Arcanic Pulsar', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-51', name: 'Balance of All Things', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-52', name: 'Timeworn Dreambinder', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-53', name: 'Frenzyband', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-54', name: 'Apex Predator\'s Craving', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-55', name: 'Eye of Fearful Symmetry', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-56', name: 'Cat-Eye Curio', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-57', name: 'Luffa-Infused Embrace', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-58', name: 'The Natural Order\'s Will', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-59', name: 'Ursoc\'s Fury Remembered', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-60', name: 'Legacy of the Sleeper', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-61', name: 'Memory of the Mother Tree', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-62', name: 'The Dark Titan\'s Lesson', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-63', name: 'Verdant Infusion', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-64', name: 'Vision of Unending Growth', type: 'sanctum-legendary', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-65', name: 'Kindred Affinity', type: 'sanctum-legendary', covenant: 'Kyrian', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-66', name: 'Celestial Spirits', type: 'sanctum-legendary', covenant: 'Night Fae', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-67', name: 'Unbridled Swarm', type: 'sanctum-legendary', covenant: 'Necrolord', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-68', name: 'Sinful Hysteria', type: 'sanctum-legendary', covenant: 'Venthyr', classes: [ 'Druid' ] },
        { key: 'sanctum-legendaries-69', name: 'Call of the Wild', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-70', name: 'Nesingwary\'s Trapping Apparatus', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-71', name: 'Soulforge Embers', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-72', name: 'Craven Strategem', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-73', name: 'Dire Command', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-74', name: 'Flamewaker\'s Cobra Sting', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-75', name: 'Qa\'pla, Eredun War Order', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-76', name: 'Rylakstalker\'s Piercing Fangs', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-77', name: 'Eagletalon\'s True Focus', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-78', name: 'Surging Shots', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-79', name: 'Serpentstalker\'s Trickery', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-80', name: 'Secrets of the Unblinking Vigil', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-81', name: 'Wildfire Cluster', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-82', name: 'Rylakstalker\'s Confounding Strikes', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-83', name: 'Latent Poison Injectors', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-84', name: 'Butcher\'s Bone Fragments', type: 'sanctum-legendary', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-85', name: 'Pact of the Soulstalkers', type: 'sanctum-legendary', covenant: 'Kyrian', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-86', name: 'Fragments of the Elder Antlers', type: 'sanctum-legendary', covenant: 'Night Fae', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-87', name: 'Bag of Munitions', type: 'sanctum-legendary', covenant: 'Necrolord', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-88', name: 'Pouch of Razor Fragments', type: 'sanctum-legendary', covenant: 'Venthyr', classes: [ 'Hunter' ] },
        { key: 'sanctum-legendaries-89', name: 'Slick Ice', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-90', name: 'Cold Front', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-91', name: 'Freezing Winds', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-92', name: 'Glacial Fragments', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-93', name: 'Expanded Potential', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-94', name: 'Disciplinary Command', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-95', name: 'Grisly Icicle', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-96', name: 'Temporal Warp', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-97', name: 'Fevered Incantation', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-98', name: 'Firestorm', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-99', name: 'Molten Skyfall', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-100', name: 'Sun King\'s Blessing', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-101', name: 'Arcane Infinity', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-102', name: 'Arcane Bombardment', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-103', name: 'Siphon Storm', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-104', name: 'Triune Ward', type: 'sanctum-legendary', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-105', name: 'Harmonic Echo', type: 'sanctum-legendary', covenant: 'Kyrian', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-106', name: 'Heart of the Fae', type: 'sanctum-legendary', covenant: 'Night Fae', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-107', name: 'Death\'s Fathom', type: 'sanctum-legendary', covenant: 'Necrolord', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-108', name: 'Sinful Delight', type: 'sanctum-legendary', covenant: 'Venthyr', classes: [ 'Mage' ] },
        { key: 'sanctum-legendaries-109', name: 'Escape from Reality', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-110', name: 'Invoker\'s Delight', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-111', name: 'Swiftsure Wraps', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-112', name: 'Fatal Touch', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-113', name: 'Charred Passions', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-114', name: 'Stormstout\'s Last Keg', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-115', name: 'Celestial Infusion', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-116', name: 'Shaohao\'s Might', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-117', name: 'Ancient Teachings of the Monastery', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-118', name: 'Yu\'lon\'s Whisper', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-119', name: 'Clouded Focus', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-120', name: 'Tear of Morning', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-121', name: 'Xuen\'s Treasure', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-122', name: 'Keefer\'s Skyreach', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-123', name: 'Jade Ignition', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-124', name: 'Last Emperor\'s Capacitor', type: 'sanctum-legendary', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-125', name: 'Call to Arms', type: 'sanctum-legendary', covenant: 'Kyrian', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-126', name: 'Faeline Harmony', type: 'sanctum-legendary', covenant: 'Night Fae', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-127', name: 'Bountiful Brew', type: 'sanctum-legendary', covenant: 'Necrolord', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-128', name: 'Sinister Teachings', type: 'sanctum-legendary', covenant: 'Venthyr', classes: [ 'Monk' ] },
        { key: 'sanctum-legendaries-129', name: 'Uther\'s Devotion', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-130', name: 'Of Dusk and Dawn', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-131', name: 'The Mad Paragon', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-132', name: 'The Magistrate\'s Judgment', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-133', name: 'Maraad\'s Dying Breath', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-134', name: 'Shock Barrier', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-135', name: 'Shadowbreaker, Dawn of the Sun', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-136', name: 'Inflorescence of the Sunwell', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-137', name: 'Holy Avenger\'s Engraved Sigil', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-138', name: 'The Ardent Protector\'s Sanctum', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-139', name: 'Bulwark of Righteous Fury', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-140', name: 'Reign of Endless Kings', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-141', name: 'Tempest of the Lightbringer', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-142', name: 'Relentless Inquisitor', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-143', name: 'Vanguard\'s Momentum', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-144', name: 'Final Verdict', type: 'sanctum-legendary', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-145', name: 'Divine Resonance', type: 'sanctum-legendary', covenant: 'Kyrian', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-146', name: 'Seasons of Plenty', type: 'sanctum-legendary', covenant: 'Night Fae', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-147', name: 'Duty-Bound Gavel', type: 'sanctum-legendary', covenant: 'Necrolord', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-148', name: 'Radiant Embers', type: 'sanctum-legendary', covenant: 'Venthyr', classes: [ 'Paladin' ] },
        { key: 'sanctum-legendaries-149', name: 'Measured Contemplation', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-150', name: 'Twins of the Sun Priestess', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-151', name: 'Cauterizing Shadows', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-152', name: 'Vault of Heavens', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-153', name: 'The Penitent One', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-154', name: 'Crystalline Reflection', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-155', name: 'Kiss of Death', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-156', name: 'Clarity of Mind', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-157', name: 'X\'anshi, Return of Archbishop Benedictus', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-158', name: 'Harmonious Apparatus', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-159', name: 'Flash Concentration', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-160', name: 'Divine Image', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-161', name: 'Painbreaker Psalm', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-162', name: 'Shadowflame Prism', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-163', name: 'Eternal Call to the Void', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-164', name: 'Talbadar\'s Stratagem', type: 'sanctum-legendary', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-165', name: 'Spheres\' Harmony', type: 'sanctum-legendary', covenant: 'Kyrian', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-166', name: 'Bwonsamdi\'s Pact', type: 'sanctum-legendary', covenant: 'Night Fae', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-167', name: 'Pallid Command', type: 'sanctum-legendary', covenant: 'Necrolord', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-168', name: 'Shadow Word: Manipulation', type: 'sanctum-legendary', covenant: 'Venthyr', classes: [ 'Priest' ] },
        { key: 'sanctum-legendaries-169', name: 'Invigorating Shadowdust', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-170', name: 'Essence of Bloodfang', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-171', name: 'Tiny Toxic Blade', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-172', name: 'Mark of the Master Assassin', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-173', name: 'Dashing Scoundrel', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-174', name: 'Doomblade', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-175', name: 'Zoldyck Insignia', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-176', name: 'Duskwalker\'s Patch', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-177', name: 'Concealed Blunderbuss', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-178', name: 'Celerity', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-179', name: 'Guile Charm', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-180', name: 'Greenskin\'s Wickers', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-181', name: 'Finality', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-182', name: 'Akaari\'s Soul Fragment', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-183', name: 'The Rotten', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-184', name: 'Deathly Shadows', type: 'sanctum-legendary', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-185', name: 'Resounding Clarity', type: 'sanctum-legendary', covenant: 'Kyrian', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-186', name: 'Toxic Onslaught', type: 'sanctum-legendary', covenant: 'Night Fae', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-187', name: 'Deathspike', type: 'sanctum-legendary', covenant: 'Necrolord', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-188', name: 'Obedience', type: 'sanctum-legendary', covenant: 'Venthyr', classes: [ 'Rogue' ] },
        { key: 'sanctum-legendaries-189', name: 'Ancestral Reminder', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-190', name: 'Deeptremor Stone', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-191', name: 'Deeply Rooted Elements', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-192', name: 'Chains of Devastation', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-193', name: 'Skybreaker\'s Fiery Demise', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-194', name: 'Elemental Equilibrium', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-195', name: 'Echoes of Great Sundering', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-196', name: 'Windspeaker\'s Lava Resurgence', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-197', name: 'Doom Winds', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-198', name: 'Legacy of the Frost Witch', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-199', name: 'Witch Doctor\'s Wolf Bones', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-200', name: 'Primal Lava Actuators', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-201', name: 'Jonat\'s Natural Focus', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-202', name: 'Spiritwalker\'s Tidal Totem', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-203', name: 'Primal Tide Core', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-204', name: 'Earthen Harmony', type: 'sanctum-legendary', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-205', name: 'Raging Vesper Vortex', type: 'sanctum-legendary', covenant: 'Kyrian', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-206', name: 'Seeds of Rampant Growth', type: 'sanctum-legendary', covenant: 'Night Fae', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-207', name: 'Splintered Elements', type: 'sanctum-legendary', covenant: 'Necrolord', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-208', name: 'Elemental Conduit', type: 'sanctum-legendary', covenant: 'Venthyr', classes: [ 'Shaman' ] },
        { key: 'sanctum-legendaries-209', name: 'Wilfred\'s Sigil of Superior Summoning', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-210', name: 'Claw of Endereth', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-211', name: 'Relic of Demonic Synergy', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-212', name: 'Pillars of the Dark Portal', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-213', name: 'Perpetual Agony of Azj\'Aqir', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-214', name: 'Sacrolash\'s Dark Strike', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-215', name: 'Malefic Wrath', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-216', name: 'Wrath of Consumption', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-217', name: 'Implosive Potential', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-218', name: 'Grim Inquisitor\'s Dread Calling', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-219', name: 'Forces of the Horned Nightmare', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-220', name: 'Balespider\'s Burning Core', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-221', name: 'Odr, Shawl of the Ymirjar', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-222', name: 'Cinders of the Azj\'Aqir', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-223', name: 'Madness of the Azj\'Aqir', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-224', name: 'Embers of the Diabolic Raiment', type: 'sanctum-legendary', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-225', name: 'Languishing Soul Detritus', type: 'sanctum-legendary', covenant: 'Kyrian', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-226', name: 'Decaying Soul Satchel', type: 'sanctum-legendary', covenant: 'Night Fae', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-227', name: 'Shard of Annihilation', type: 'sanctum-legendary', covenant: 'Necrolord', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-228', name: 'Contained Perpetual Explosion', type: 'sanctum-legendary', covenant: 'Venthyr', classes: [ 'Warlock' ] },
        { key: 'sanctum-legendaries-229', name: 'Leaper', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-230', name: 'Seismic Reverberation', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-231', name: 'Misshapen Mirror', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-232', name: 'Signet of Tormented Kings', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-233', name: 'Enduring Blow', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-234', name: 'Battlelord', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-235', name: 'Exploiter', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-236', name: 'Unhinged', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-237', name: 'Cadence of Fujieda', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-238', name: 'Deathmaker', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-239', name: 'Reckless Defense', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-240', name: 'Will of the Berserker', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-241', name: 'Thunderlord', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-242', name: 'The Wall', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-243', name: 'Unbreakable Will', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-244', name: 'Reprisal', type: 'sanctum-legendary', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-245', name: 'Elysian Might', type: 'sanctum-legendary', covenant: 'Kyrian', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-246', name: 'Nature\'s Fury', type: 'sanctum-legendary', covenant: 'Night Fae', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-247', name: 'Glory', type: 'sanctum-legendary', covenant: 'Necrolord', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-248', name: 'Sinful Surge', type: 'sanctum-legendary', covenant: 'Venthyr', classes: [ 'Warrior' ] },
        { key: 'sanctum-legendaries-249', name: 'Unity', type: 'sanctum-legendary' },
    ],
};

export {
    data,
};
